name: Deploy to AWS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  job1:
    name: build_ecr
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
          role-to-assume: arn:aws:iam::320514709580:role/GitHubActionsRepoApp
          aws-region: us-east-2

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2.0.1

      - name: Build, tag, and push image to Amazon ECR
        run: |
          docker build -t my-app:v1.0 .
          docker tag my-app:v1.0 320514709580.dkr.ecr.us-east-2.amazonaws.com/node-prod:v1.0
          docker push 320514709580.dkr.ecr.us-east-2.amazonaws.com/node-prod:v1.0
  
  job2:
    name: deploy_ec2
    needs: job1
    env:
      INSTANCE_KEY: ${{secrets.INSTANCE_KEY}}
    runs-on: ubuntu-latest
    steps:
     - name: Configure AWS Credentials
       uses: aws-actions/configure-aws-credentials@v4.3.1
       with:
         role-to-assume: arn:aws:iam::320514709580:role/GitHubActionsRepoApp
         aws-region: us-east-2

     - name: Get EC2 IP from SSM
       run: |
         EC2_IP=$(aws ssm get-parameter \
           --name "/meu-projeto/prod/ec2/node-server/public_ip" \
           --query "Parameter.Value" \
           --output text)

         echo "EC2_IP=$EC2_IP" >> $GITHUB_ENV

     - name: Deploy to EC2 via SSH
       run: |
          echo "$INSTANCE_KEY" > chave-node.pem
          chmod 400 chave-node.pem
          ssh -i chave-node.pem -o StrictHostKeyChecking=no ec2-user@$EC2_IP << 'EOF'
            aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 320514709580.dkr.ecr.us-east-2.amazonaws.com
            docker pull 320514709580.dkr.ecr.us-east-2.amazonaws.com/node-prod:v1.0
            echo "Stopping old Docker container..."
            docker stop node || true
            echo "Removing old Docker container..."
            docker rm node || true
            echo "Starting new Docker container..."
            docker run -d -p 80:80 --name node 320514709580.dkr.ecr.us-east-2.amazonaws.com/node-prod:v1.0
            docker ps
          EOF
          rm -f chave-node.pem
